import Head from 'next/head'

import {MetaData} from '../component'

export default function Home()
{
  return (
    <div>
      <Head>
        <title></title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <MetaData />

    </div>
  )
}
